name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: build
        run: |
          make -C src/micropython/mpy-cross
          make TARGET=NANO33 -C src
          mkdir ~/build/NANO33
          cp -r src/build/bin/* ~/build/NANO33
